In [1]:
import numpy as np
import cv2
import os
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.0001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('./CalibImages/*.JPG')

for fname in images:
    img = cv2.imread(fname)

    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (7,6),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners)

        # Draw and display the corners
        #cv2.drawChessboardCorners(img, (7,6), corners,ret)
        #cv2.imshow('img',img)
        #cv2.waitKey(500)

#cv2.destroyAllWindows()

ret2, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

mean_error = 0.0000
tot_error = 0.0000

for i in xrange(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    tot_error += error

print 'total error: ', mean_error/len(objpoints)

total error:  0.0


In [5]:
print 'Camera matrix: \n', mtx
print 'Distortion coefficients: \n', dist
print 'Rotation vector: \n', rvecs
print 'Translation vector: \n', tvecs

Camera matrix: 
[[3.27894981e+03 0.00000000e+00 2.05358222e+03]
 [0.00000000e+00 3.29320263e+03 1.49021929e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion coefficients: 
[[ 2.83092458e-01 -1.66799155e+00 -1.62644698e-03  4.04708463e-04
   3.04420786e+00]]
Rotation vector: 
[array([[ 0.22858952],
       [-0.05937148],
       [ 0.02399552]]), array([[-0.20254259],
       [-0.09617585],
       [-0.02992782]]), array([[ 0.01236527],
       [-0.16722998],
       [-0.14128718]]), array([[-0.0759229 ],
       [-0.32239681],
       [ 0.29888385]]), array([[-0.24347854],
       [-0.07608671],
       [ 0.10121536]]), array([[-0.02542351],
       [-0.05628719],
       [-0.01010491]])]
Translation vector: 
[array([[-1.904761  ],
       [-1.9479296 ],
       [ 8.37920347]]), array([[-1.96385277],
       [-2.73899755],
       [ 9.41938815]]), array([[-1.75248331],
       [-2.30743998],
       [ 9.3139964 ]]), array([[ 0.2543675 ],
       [-2.49115005],
       [10.87343066]]), array(